"""Configuration file generation for Pongogo."""

from pathlib import Path
from typing import Any, cast

import yaml

DEFAULT_CONFIG: dict[str, Any] = {
    "version": "1.0.0",
    "categories": {
        "software_engineering": True,
        "project_management": True,
        "agentic_workflows": True,
        "architecture": True,
        "quality": True,
        "safety_prevention": True,
        "testing": True,
        "validation": True,
        "devops": True,
        "development": True,
        "github_integration": True,
        "trust_execution": True,
    },
    "placeholders": {
        "wiki_path": "wiki/",
        "docs_path": "docs/",
        "owner_repo": "",
        "instructions_path": ".pongogo/instructions/",
    },
}

MINIMAL_CATEGORIES = {
    "software_engineering",
    "safety_prevention",
}

CONFIG_HEADER = """\
# Pongogo Configuration
# Generated by: pongogo init
# Documentation: https://github.com/pongogo/pongogo-to-go
#
# Categories: Enable/disable instruction categories
# Placeholders: Customize paths and identifiers for your project

"""


def generate_config(
    minimal: bool = False,
    wiki_path: str | None = None,
    docs_path: str | None = None,
) -> dict[str, Any]:
    """Generate configuration dictionary.

    Args:
        minimal: If True, only enable core categories
        wiki_path: Detected/created wiki folder path (relative to project root)
        docs_path: Detected/created docs folder path (relative to project root)

    Returns:
        Configuration dictionary
    """
    config = DEFAULT_CONFIG.copy()
    config["categories"] = DEFAULT_CONFIG["categories"].copy()
    config["placeholders"] = DEFAULT_CONFIG["placeholders"].copy()

    if minimal:
        for category in config["categories"]:
            config["categories"][category] = category in MINIMAL_CATEGORIES

    # Update placeholders with detected/created paths
    if wiki_path:
        config["placeholders"]["wiki_path"] = wiki_path
    if docs_path:
        config["placeholders"]["docs_path"] = docs_path

    return config


def write_config(config_path: Path, config: dict[str, Any]) -> None:
    """Write configuration to YAML file.

    Args:
        config_path: Path to write config file
        config: Configuration dictionary
    """
    config_path.parent.mkdir(parents=True, exist_ok=True)

    with open(config_path, "w") as f:
        f.write(CONFIG_HEADER)
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)


def load_config(config_path: Path) -> dict[str, Any]:
    """Load configuration from YAML file.

    Args:
        config_path: Path to config file

    Returns:
        Configuration dictionary
    """
    with open(config_path) as f:
        return cast(dict[str, Any], yaml.safe_load(f))
